version: "3.8"
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: git_like_db
      POSTGRES_PASSWORD: postgres123
      POSTGRES_USER: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
